package com.baize.flux.server.runtime;
import com.baize.flux.framework.execution.*; import com.baize.flux.framework.job.*; import com.baize.flux.framework.metrics.*; import java.text.SimpleDateFormat; import java.util.*; import java.util.concurrent.*; import java.util.concurrent.atomic.AtomicLong;
/** 单机作业协调器：HTTP 线程只提交任务，真正执行和取消均委托给引擎。 */
public final class LocalJobManager implements JobManager {
 private final ExecutorService executor; private final ConcurrentMap<String,JobExecutionHandle> running=new ConcurrentHashMap<String,JobExecutionHandle>(); private final ConcurrentMap<String,JobSnapshot> finished=new ConcurrentHashMap<String,JobSnapshot>(); private final AtomicLong sequence=new AtomicLong(); private volatile boolean closed;
 public LocalJobManager(int threads){executor=Executors.newFixedThreadPool(Math.max(1,threads));}
 public String submit(final JobDefinition d){if(closed)throw new IllegalStateException("Job manager is closed"); final String id="flux-"+new SimpleDateFormat("yyyyMMddHHmmssSSS").format(new Date())+"-"+sequence.incrementAndGet(); final JobExecutionHandle h=new JobExecutionHandle(id,d.getName()); running.put(id,h); try {h.future=executor.submit(new Runnable(){public void run(){run(d,h);}});}catch(RuntimeException e){running.remove(id);throw e;} return id;}
 private void run(JobDefinition d,JobExecutionHandle h){h.start=System.currentTimeMillis(); synchronized(h){if(h.status==ServerJobStatus.SUBMITTED)h.status=ServerJobStatus.RUNNING;} try { LocalFluxEngine engine=LocalFluxEngine.create(Thread.currentThread().getContextClassLoader()); JobResult result=engine.execute(d,new JobExecutionListener(){public void onJobExecutionCreated(JobExecution e){h.execution=e; if(h.status==ServerJobStatus.CANCELLING)e.cancel();}}); h.end=System.currentTimeMillis(); ServerJobStatus s=h.status==ServerJobStatus.CANCELLING||result.getStatus()==JobStatus.CANCELED?ServerJobStatus.CANCELED:result.getStatus()==JobStatus.SUCCEEDED?ServerJobStatus.SUCCEEDED:ServerJobStatus.FAILED; finished.put(h.id,snapshot(h,result,s,null)); } catch(Throwable e){h.end=System.currentTimeMillis(); finished.put(h.id,snapshot(h,null,h.status==ServerJobStatus.CANCELLING?ServerJobStatus.CANCELED:ServerJobStatus.FAILED,e));} finally {running.remove(h.id);}}
 public JobSnapshot getJob(String id){JobExecutionHandle h=running.get(id); if(h!=null)return snapshot(h,null,h.status,null); JobSnapshot s=finished.get(id);if(s==null)throw new NoSuchElementException("Job not found: "+id);return s;}
 public List<JobSnapshot> listJobs(){List<JobSnapshot> all=new ArrayList<JobSnapshot>(finished.values());for(JobExecutionHandle h:running.values())all.add(snapshot(h,null,h.status,null));Collections.sort(all,new Comparator<JobSnapshot>(){public int compare(JobSnapshot a,JobSnapshot b){return Long.compare(b.getCreateTimeMillis(),a.getCreateTimeMillis());}});return all;}
 public boolean cancel(String id){JobExecutionHandle h=running.get(id);if(h==null){if(finished.containsKey(id))throw new IllegalStateException("Job has already finished");throw new NoSuchElementException("Job not found: "+id);} synchronized(h){if(h.status!=ServerJobStatus.CANCELLING)h.cancel();}return true;}
 public void close(){closed=true;for(JobExecutionHandle h:running.values())h.cancel();executor.shutdownNow();}
 private static JobSnapshot snapshot(JobExecutionHandle h,JobResult r,ServerJobStatus status,Throwable failure){Map<String,Object> m=new LinkedHashMap<String,Object>(),c=new LinkedHashMap<String,Object>();List<Map<String,Object>> ps=new ArrayList<Map<String,Object>>(); if(r!=null){JobMetrics x=r.getMetrics();m.put("sourceBatchCount",x.getSourceBatchCount());m.put("sourceRecordCount",x.getSourceRecordCount());m.put("sourceAverageQps",x.getSourceAverageQps());m.put("sinkReceivedBatchCount",x.getSinkReceivedBatchCount());m.put("sinkAttemptedRecordCount",x.getSinkAttemptedRecordCount());m.put("sinkSuccessRecordCount",x.getSinkRecordCount());m.put("unknownStateRecordCount",x.getUnknownStateRecordCount()); CommitSummary q=r.getCommitSummary();c.put("successfullyCommittedRecordCount",q.getSuccessfullyCommittedRecordCount());c.put("dataCommittedTaskCount",q.getDataCommittedTaskCount());c.put("emptyCommittedTaskCount",q.getEmptyCommittedTaskCount());c.put("failedOrUncommittedTaskCount",q.getFailedOrUncommittedTaskCount());c.put("partialTaskCommit",q.isPartialTaskCommit());c.put("partialDataCommit",q.isPartialDataCommit());c.put("retryAdvice",q.getRetryAdvice());for(PipelineResult p:r.getPipelineResults()){Map<String,Object> v=new LinkedHashMap<String,Object>();v.put("pipelineId",p.getPipelineId());v.put("dataSetId",p.getDataSetId());v.put("status",p.getStatus());v.put("source",endpoint(p.getSourceIdentifier(),p.getSourceTable(),p.getSourceTaskCount()));v.put("sink",endpoint(p.getSinkIdentifier(),p.getSinkTable(),p.getSinkTaskCount()));ps.add(v);}} Throwable e=failure==null&&r!=null?r.getFailure():failure;return new JobSnapshot(h.id,h.name,status,h.create,h.start,h.end,m,c,ps,e==null?null:"FLUX-JOB-FAILED",e==null?null:safe(e));}
 private static Map<String,Object> endpoint(String connector,String table,int count){Map<String,Object> x=new LinkedHashMap<String,Object>();x.put("connector",connector);x.put("table",table);x.put("taskCount",count);return x;} private static String safe(Throwable e){String s=e.getMessage();return s==null?e.getClass().getSimpleName():s.length()>500?s.substring(0,500):s;}
}
